/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InsertRemove;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author xavier
 */
public class PeopleList extends javax.swing.JFrame {

    ArrayList<Person> people = new ArrayList();
    DefaultListModel list = new DefaultListModel();

    public PeopleList() {
        initComponents();
        people.add(new Person("Bob",25,"M"));
        people.add(new Person("Fran",55,"O"));
        people.add(new Person("Mark",15,"M"));
        people.add(new Person("Sue",30,"F"));
        PeopleLST.setModel(list);
        for(Person p: people){
            list.addElement(p.getName());
        }
    }
    
    public void ClearForm(){
        TXTName.setText("");
        TXTAge.setText("");
        buttonGroup1.clearSelection();
        PeopleLST.clearSelection();
    }
    
    public void show(Person p){
        TXTName.setText(p.getName());
        TXTAge.setText("" + p.getAge());
        if(p.getGender() == "M")
            MaleRB.setSelected(true);
        else
            FemaleRB.setSelected(true);
        
        
    }
    
    public static int search(ArrayList a, Object searchValue) {
        int left = 0;
        int right = a.size() - 1;
        while (left <= right) {
            int midpoint = (left + right) / 2;
            int result = ((Comparable) a.get(midpoint)).compareTo(searchValue);
            if (result == 0) {
                return midpoint;
            } else if (result < 0) {
                left = midpoint + 1;
            } else {
                right = midpoint - 1;
            }
        }
        return -1;
    }
    
    public static int findInsertPoint (ArrayList a, Object searchValue){
	   int left = 0;
	   int right = a.size()-1;
	   int midpoint=0;
           int result=0;
	   
	   while (left <= right){
	      midpoint = (left + right) / 2;
	      result = ((Comparable)a.get(midpoint)).compareTo(searchValue); 
	   
	     if (result < 0)
	         left = midpoint + 1;
	      else
	         right = midpoint-1;
	   }
	   if(result < 0)
	   midpoint++;
	   return midpoint;	   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        PeopleLST = new javax.swing.JList<>();
        TXTName = new javax.swing.JTextField();
        TXTAge = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        MaleRB = new javax.swing.JRadioButton();
        FemaleRB = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        ExitMNU = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AddMNU = new javax.swing.JMenuItem();
        ClearMNU = new javax.swing.JMenuItem();
        DeleteMNU = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        AllMNU = new javax.swing.JMenuItem();
        MalesMNU = new javax.swing.JMenuItem();
        FemalesMnu = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PeopleLST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PeopleLSTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PeopleLST);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MaleRB.setText("Male");

        FemaleRB.setText("Female");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(MaleRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(FemaleRB)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FemaleRB)
                    .addComponent(MaleRB))
                .addContainerGap())
        );

        jLabel1.setText("Name");

        jLabel2.setText("Age");

        jMenu2.setText("File");

        ExitMNU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InsertRemove/exit.png"))); // NOI18N
        ExitMNU.setText("Exit");
        ExitMNU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMNUActionPerformed(evt);
            }
        });
        jMenu2.add(ExitMNU);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");

        AddMNU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InsertRemove/insert.png"))); // NOI18N
        AddMNU.setText("Add");
        AddMNU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMNUActionPerformed(evt);
            }
        });
        jMenu3.add(AddMNU);

        ClearMNU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InsertRemove/exit.png"))); // NOI18N
        ClearMNU.setText("Clear");
        ClearMNU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearMNUActionPerformed(evt);
            }
        });
        jMenu3.add(ClearMNU);

        DeleteMNU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InsertRemove/delete.png"))); // NOI18N
        DeleteMNU.setText("Delete");
        jMenu3.add(DeleteMNU);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Filter");

        AllMNU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InsertRemove/all.png"))); // NOI18N
        AllMNU.setText("Show All");
        jMenu4.add(AllMNU);

        MalesMNU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InsertRemove/male.png"))); // NOI18N
        MalesMNU.setText("Males");
        jMenu4.add(MalesMNU);

        FemalesMnu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InsertRemove/female.png"))); // NOI18N
        FemalesMnu.setText("Females");
        jMenu4.add(FemalesMnu);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXTAge)
                    .addComponent(TXTName)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearMNUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearMNUActionPerformed
        ClearForm();
    }//GEN-LAST:event_ClearMNUActionPerformed

    private void ExitMNUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMNUActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitMNUActionPerformed

    private void PeopleLSTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeopleLSTMouseClicked
        String name = "" + PeopleLST.getSelectedValue();
        int loc = search(people, new Person(name,0,""));
        show(people.get(loc));
    }//GEN-LAST:event_PeopleLSTMouseClicked

    private void AddMNUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMNUActionPerformed
        String Name = TXTName.getText();
        int Age = Integer.parseInt(TXTAge.getText());
        String Gender = buttonGroup1.getSelection().getActionCommand();
        int loc = findInsertPoint(people,Name);
        people.add(loc,(new Person(Name,Age,Gender)));
        show(people.get(loc));
    }//GEN-LAST:event_AddMNUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeopleList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeopleList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeopleList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeopleList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeopleList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddMNU;
    private javax.swing.JMenuItem AllMNU;
    private javax.swing.JMenuItem ClearMNU;
    private javax.swing.JMenuItem DeleteMNU;
    private javax.swing.JMenuItem ExitMNU;
    private javax.swing.JRadioButton FemaleRB;
    private javax.swing.JMenuItem FemalesMnu;
    private javax.swing.JRadioButton MaleRB;
    private javax.swing.JMenuItem MalesMNU;
    private javax.swing.JList<String> PeopleLST;
    private javax.swing.JTextField TXTAge;
    private javax.swing.JTextField TXTName;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
